# Generated by Django 4.2 on 2023-04-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booklist',
        ),
        migrations.AddField(
            model_name='order',
            name='Books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
    ]
